App.project = App.cable.subscriptions.create "ProjectChannel",
  connected: ->
    # Called when the subscription is ready for use on the server

  disconnected: ->
    # Called when the subscription has been terminated by the server

  received: (data) ->
    $('#project_detail').html(data['project_detail'])
    identifier = 'li.project-'+data['slug']
    $(identifier).fadeOut 300, ->
      $(identifier).replaceWith(data['content'])
      $(identifier).fadeIn 300
      return

    # ---
    # generated by js2coffee 2.2.0

  contribute: (slug, name, email, value_to_pass) ->
    @perform 'contribute', slug: slug, name: name, email: email, value_to_pass: value_to_pass
